using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog_App_MVC.Models
{
    public class Db
    {
        public List<Post> posts { get; set; }
        public static Db Instance
        {
            get
            {
                return _instance ?? (_instance = CreateDb());
            }
        }
        private static Db _instance;

        private static Db CreateDb()
        {
            return new Db()
            {
                posts = new List<Post>()
                {
           
                    new Post("Brand New Developments In Tech", "Slow-carb Carles Schlitz, hella art party literally freegan street art fashion axe flannel craft beer Godard Thundercats shabby chic authentic. Biodiesel iPhone single-origin coffee, hashtag four dollar toast twee meh drinking vinegar. Yr tilde bitters Etsy Carles, pour-over sustainable dreamcatcher Intelligentsia vinyl health goth banh mi PBR Kickstarter pug. Migas Bushwick McSweeney's, typewriter Truffaut VHS meh Vice hashtag pour-over authentic salvia art party. Brunch synth Kickstarter Marfa, cliche health goth kale chips beard. Narwhal ugh farm-to-table, cred crucifix put a bird on it lumbersexual gastropub quinoa kale chips chambray flexitarian. Four loko squid cred hashtag. Pinterest street art cliche taxidermy, slow-carb before they sold out Intelligentsia cold-pressed bicycle rights dreamcatcher kale chips whatever meditation. Lo-fi polaroid trust fund photo booth. Keytar American Apparel lo-fi selfies, hashtag Godard slow-carb paleo squid yr Pitchfork pork belly mlkshk. +1 Helvetica paleo letterpress lomo Vice, kale chips vegan. Migas cold-pressed swag, banjo synth farm-to-table Schlitz bespoke flexitarian kogi banh mi Etsy. Narwhal +1 taxidermy art party you probably haven't heard of them four dollar toast kale chips, lumbersexual Schlitz actually occupy sartorial. Chillwave direct trade synth flexitarian. Readymade fixie Helvetica, Blue Bottle Odd Future you probably haven't heard of them ethical drinking vinegar chillwave. Flexitarian jean shorts put a bird on it food truck Schlitz Kickstarter, pug shabby chic. Carles disrupt Tumblr cronut ennui, vegan mumblecore. Flannel church-key Blue Bottle Pinterest sustainable gastropub, artisan readymade street art craft beer Banksy beard. Gastropub put a bird on it kitsch, food truck gentrify pickled migas locavore. Beard cronut viral, shabby chic kogi American Apparel gastropub mumblecore authentic vegan put a bird on it sustainable migas slow-carb locavore. Crucifix chambray four loko, fap locavore Austin aesthetic forage", DateTime.Now, "Me", 1, new List<string> {"Hello, world."}),
                    new Post("7 Weird Ways To Get Things Done", "Slow-carb Carles Schlitz, hella art party literally freegan street art fashion axe flannel craft beer Godard Thundercats shabby chic authentic. Biodiesel iPhone single-origin coffee, hashtag four dollar toast twee meh drinking vinegar. Yr tilde bitters Etsy Carles, pour-over sustainable dreamcatcher Intelligentsia vinyl health goth banh mi PBR Kickstarter pug. Migas Bushwick McSweeney's, typewriter Truffaut VHS meh Vice hashtag pour-over authentic salvia art party. Brunch synth Kickstarter Marfa, cliche health goth kale chips beard. Narwhal ugh farm-to-table, cred crucifix put a bird on it lumbersexual gastropub quinoa kale chips chambray flexitarian. Four loko squid cred hashtag. Pinterest street art cliche taxidermy, slow-carb before they sold out Intelligentsia cold-pressed bicycle rights dreamcatcher kale chips whatever meditation. Lo-fi polaroid trust fund photo booth. Keytar American Apparel lo-fi selfies, hashtag Godard slow-carb paleo squid yr Pitchfork pork belly mlkshk. +1 Helvetica paleo letterpress lomo Vice, kale chips vegan. Migas cold-pressed swag, banjo synth farm-to-table Schlitz bespoke flexitarian kogi banh mi Etsy. Narwhal +1 taxidermy art party you probably haven't heard of them four dollar toast kale chips, lumbersexual Schlitz actually occupy sartorial. Chillwave direct trade synth flexitarian. Readymade fixie Helvetica, Blue Bottle Odd Future you probably haven't heard of them ethical drinking vinegar chillwave. Flexitarian jean shorts put a bird on it food truck Schlitz Kickstarter, pug shabby chic. Carles disrupt Tumblr cronut ennui, vegan mumblecore. Flannel church-key Blue Bottle Pinterest sustainable gastropub, artisan readymade street art craft beer Banksy beard. Gastropub put a bird on it kitsch, food truck gentrify pickled migas locavore. Beard cronut viral, shabby chic kogi American Apparel gastropub mumblecore authentic vegan put a bird on it sustainable migas slow-carb locavore. Crucifix chambray four loko, fap locavore Austin aesthetic forage", DateTime.Now, "Me", 2, new List<string> {"Hello, world."}), 
                    new Post("How To Get Started With Ruby", "Slow-carb Carles Schlitz, hella art party literally freegan street art fashion axe flannel craft beer Godard Thundercats shabby chic authentic. Biodiesel iPhone single-origin coffee, hashtag four dollar toast twee meh drinking vinegar. Yr tilde bitters Etsy Carles, pour-over sustainable dreamcatcher Intelligentsia vinyl health goth banh mi PBR Kickstarter pug. Migas Bushwick McSweeney's, typewriter Truffaut VHS meh Vice hashtag pour-over authentic salvia art party. Brunch synth Kickstarter Marfa, cliche health goth kale chips beard. Narwhal ugh farm-to-table, cred crucifix put a bird on it lumbersexual gastropub quinoa kale chips chambray flexitarian. Four loko squid cred hashtag. Pinterest street art cliche taxidermy, slow-carb before they sold out Intelligentsia cold-pressed bicycle rights dreamcatcher kale chips whatever meditation. Lo-fi polaroid trust fund photo booth. Keytar American Apparel lo-fi selfies, hashtag Godard slow-carb paleo squid yr Pitchfork pork belly mlkshk. +1 Helvetica paleo letterpress lomo Vice, kale chips vegan. Migas cold-pressed swag, banjo synth farm-to-table Schlitz bespoke flexitarian kogi banh mi Etsy. Narwhal +1 taxidermy art party you probably haven't heard of them four dollar toast kale chips, lumbersexual Schlitz actually occupy sartorial. Chillwave direct trade synth flexitarian. Readymade fixie Helvetica, Blue Bottle Odd Future you probably haven't heard of them ethical drinking vinegar chillwave. Flexitarian jean shorts put a bird on it food truck Schlitz Kickstarter, pug shabby chic. Carles disrupt Tumblr cronut ennui, vegan mumblecore. Flannel church-key Blue Bottle Pinterest sustainable gastropub, artisan readymade street art craft beer Banksy beard. Gastropub put a bird on it kitsch, food truck gentrify pickled migas locavore. Beard cronut viral, shabby chic kogi American Apparel gastropub mumblecore authentic vegan put a bird on it sustainable migas slow-carb locavore. Crucifix chambray four loko, fap locavore Austin aesthetic forage", DateTime.Now, "Me", 3, new List<string> {"Hello, world."}),
                    new Post("Top Ten Tech Companies To Get Hired At", "Slow-carb Carles Schlitz, hella art party literally freegan street art fashion axe flannel craft beer Godard Thundercats shabby chic authentic. Biodiesel iPhone single-origin coffee, hashtag four dollar toast twee meh drinking vinegar. Yr tilde bitters Etsy Carles, pour-over sustainable dreamcatcher Intelligentsia vinyl health goth banh mi PBR Kickstarter pug. Migas Bushwick McSweeney's, typewriter Truffaut VHS meh Vice hashtag pour-over authentic salvia art party. Brunch synth Kickstarter Marfa, cliche health goth kale chips beard. Narwhal ugh farm-to-table, cred crucifix put a bird on it lumbersexual gastropub quinoa kale chips chambray flexitarian. Four loko squid cred hashtag. Pinterest street art cliche taxidermy, slow-carb before they sold out Intelligentsia cold-pressed bicycle rights dreamcatcher kale chips whatever meditation. Lo-fi polaroid trust fund photo booth. Keytar American Apparel lo-fi selfies, hashtag Godard slow-carb paleo squid yr Pitchfork pork belly mlkshk. +1 Helvetica paleo letterpress lomo Vice, kale chips vegan. Migas cold-pressed swag, banjo synth farm-to-table Schlitz bespoke flexitarian kogi banh mi Etsy. Narwhal +1 taxidermy art party you probably haven't heard of them four dollar toast kale chips, lumbersexual Schlitz actually occupy sartorial. Chillwave direct trade synth flexitarian. Readymade fixie Helvetica, Blue Bottle Odd Future you probably haven't heard of them ethical drinking vinegar chillwave. Flexitarian jean shorts put a bird on it food truck Schlitz Kickstarter, pug shabby chic. Carles disrupt Tumblr cronut ennui, vegan mumblecore. Flannel church-key Blue Bottle Pinterest sustainable gastropub, artisan readymade street art craft beer Banksy beard. Gastropub put a bird on it kitsch, food truck gentrify pickled migas locavore. Beard cronut viral, shabby chic kogi American Apparel gastropub mumblecore authentic vegan put a bird on it sustainable migas slow-carb locavore. Crucifix chambray four loko, fap locavore Austin aesthetic forage", DateTime.Now, "Me", 4, new List<string> {"Hello, world."}),
                    new Post("Why Your New Smartphone Sucks", "Slow-carb Carles Schlitz, hella art party literally freegan street art fashion axe flannel craft beer Godard Thundercats shabby chic authentic. Biodiesel iPhone single-origin coffee, hashtag four dollar toast twee meh drinking vinegar. Yr tilde bitters Etsy Carles, pour-over sustainable dreamcatcher Intelligentsia vinyl health goth banh mi PBR Kickstarter pug. Migas Bushwick McSweeney's, typewriter Truffaut VHS meh Vice hashtag pour-over authentic salvia art party. Brunch synth Kickstarter Marfa, cliche health goth kale chips beard. Narwhal ugh farm-to-table, cred crucifix put a bird on it lumbersexual gastropub quinoa kale chips chambray flexitarian. Four loko squid cred hashtag. Pinterest street art cliche taxidermy, slow-carb before they sold out Intelligentsia cold-pressed bicycle rights dreamcatcher kale chips whatever meditation. Lo-fi polaroid trust fund photo booth. Keytar American Apparel lo-fi selfies, hashtag Godard slow-carb paleo squid yr Pitchfork pork belly mlkshk. +1 Helvetica paleo letterpress lomo Vice, kale chips vegan. Migas cold-pressed swag, banjo synth farm-to-table Schlitz bespoke flexitarian kogi banh mi Etsy. Narwhal +1 taxidermy art party you probably haven't heard of them four dollar toast kale chips, lumbersexual Schlitz actually occupy sartorial. Chillwave direct trade synth flexitarian. Readymade fixie Helvetica, Blue Bottle Odd Future you probably haven't heard of them ethical drinking vinegar chillwave. Flexitarian jean shorts put a bird on it food truck Schlitz Kickstarter, pug shabby chic. Carles disrupt Tumblr cronut ennui, vegan mumblecore. Flannel church-key Blue Bottle Pinterest sustainable gastropub, artisan readymade street art craft beer Banksy beard. Gastropub put a bird on it kitsch, food truck gentrify pickled migas locavore. Beard cronut viral, shabby chic kogi American Apparel gastropub mumblecore authentic vegan put a bird on it sustainable migas slow-carb locavore. Crucifix chambray four loko, fap locavore Austin aesthetic forage", DateTime.Now, "Me", 5, new List<string> {"Hello, world."})
                                                            
                }
            };
        }
        private Db() 
        {
        }
    }
}